var ENUM;

ENUM = 0;
var CURSOR_NULL     = ENUM; ENUM++;
var CURSOR_NORMAL   = ENUM; ENUM++;
var CURSOR_PERSON   = ENUM; ENUM++;
var CURSOR_OBJECT   = ENUM; ENUM++;
var CURSOR_PORTHOLE = ENUM; ENUM++;
var CURSOR_VIEW     = ENUM; ENUM++;
var CURSOR_COUNT    = ENUM; ENUM++;

ENUM = 0;
var STATE_NULL       = ENUM; ENUM++;
var STATE_NAV        = ENUM; ENUM++;
var STATE_MAP        = ENUM; ENUM++;
var STATE_NOTEBOOK   = ENUM; ENUM++;
var STATE_PERSON     = ENUM; ENUM++;
var STATE_OBJECT     = ENUM; ENUM++;
var STATE_WILDCARD   = ENUM; ENUM++;
var STATE_CUTSCENE   = ENUM; ENUM++;
var STATE_TRANSITION = ENUM; ENUM++;
var STATE_COUNT      = ENUM; ENUM++;

ENUM = 0;
var ACT_NULL     = ENUM; ENUM++;
var ACT_PERSON   = ENUM; ENUM++;
var ACT_OBJECT   = ENUM; ENUM++;
var ACT_PORTHOLE = ENUM; ENUM++;
var ACT_WILDCARD = ENUM; ENUM++;
var ACT_INERT    = ENUM; ENUM++;
var ACT_COUNT    = ENUM; ENUM++;

ENUM = 0;
var ANIM_NULL  = ENUM; ENUM++;
var ANIM_IDLE  = ENUM; ENUM++;
var ANIM_WALK  = ENUM; ENUM++;
var ANIM_ACT   = ENUM; ENUM++;
var ANIM_COUNT = ENUM; ENUM++;

ENUM = 0;
var AVATAR_NULL  = ENUM; ENUM++;
var AVATAR_IDLE  = ENUM; ENUM++;
var AVATAR_WALK  = ENUM; ENUM++;
var AVATAR_ACT   = ENUM; ENUM++;
var AVATAR_COUNT = ENUM; ENUM++;

ENUM = 0;
var SPEAKER_NULL   = ENUM; ENUM++;
var SPEAKER_PLAYER = ENUM; ENUM++;
var SPEAKER_PERSON = ENUM; ENUM++;
var SPEAKER_COUNT  = ENUM; ENUM++;

ENUM = 0;
var COMMAND_NULL    = ENUM; ENUM++;
var COMMAND_CREATE  = ENUM; ENUM++;
var COMMAND_DESTROY = ENUM; ENUM++;
var COMMAND_ANIMATE = ENUM; ENUM++;
var COMMAND_TWEEN   = ENUM; ENUM++;
var COMMAND_WAIT    = ENUM; ENUM++;
var COMMAND_END     = ENUM; ENUM++;
var COMMAND_COUNT   = ENUM; ENUM++;

ENUM = 0;
var ENTITY_NULL  = ENUM; ENUM++;
var ENTITY_ANIM  = ENUM; ENUM++;
var ENTITY_TEXT  = ENUM; ENUM++;
var ENTITY_COUNT = ENUM; ENUM++;

