var quiz = {
  questions:[
    {
      q:"Is English the first language you learned?",
      a:[
        "Yes",
        "No"
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"How well do you read in English?",
      a:[
        "Not a very Good Reader",
        "An OK Reader",
        "Very Good Reader"
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"Do you Enjoy reading in English?",
      a:[
        "Really Enjoy",
        "Enjoy",
        "It's OK",
        "Do Not Enjoy"
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
  ],
};
var reset_quiz = function()
{
  for(var i = 0; i < quiz.questions.length; i++)
  {
    var q = quiz.questions[i];
    q.response = -1;
  }
}
var gen_callbacks = function()
{
  for(var i = 0; i < quiz.questions.length; i++)
  {
    var q = quiz.questions[i];
    for(var j = 0; j < q.a.length; j++)
      q.aclick[j] = (function(i, selection){
        return function() {
          if(quiz.questions[i].response == selection) {
            // if player re-clicks, deselect.
            quiz.questions[i].response = -1;
          }
          else {
            // else, select newly chosen item.
            quiz.questions[i].response = selection;
          }
        }
      })(i,j); //javascript is ridiculous
  }
}
gen_callbacks();

