var quiz0 = {
  quizn: 0,
  questions:[
    {
      q:"Is English the first language you learned?",
      a:[
        "Yes",
        "No"
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"How well do you read in English?",
      a:[
        "Not a very Good Reader",
        "An OK Reader",
        "Very Good Reader"
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"Do you Enjoy reading in English?",
      a:[
        "Really Enjoy",
        "Enjoy",
        "It's OK",
        "Do Not Enjoy"
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
  ],
};
var quiz1 = {
  quizn: 1,
  questions:[
    {
      q:"Q1.1",
      a:[
        "Strongly Disagree",
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
        "Strongly Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"Q1.2",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },    
    {
      q:"Q1.3",
      a:[
        "Strongly Disagree",
        "Disagree",
        "Somewhat Disagree",
        "Neither Agree nor Disagree",
        "Somewhat Agree",
        "Agree",
        "Strongly Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"Q1.4",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neither Agree nor Disagree",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
    {
      q:"Q1.5",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    },
  ],
};
var quiz2 = {
  quizn: 2,
  questions:[
    {
      q:"Jo is entertaining.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"The game grabs my attention.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I forget about time passing while playing the game.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I become unaware of my surroundings while while playing the game.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I feel emotionally involved in the game.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
  ],
};
var quiz3 = {
  quizn: 3,
  questions:[
    {
      q:"I like watching the TV shows of history.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I like learning about history.",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I like learning science very much",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I think learning science is fun",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Jo is friendly",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
  ],
};
var quiz4 = {
  quizn: 4,
  questions:[
    {
      q:"Jo is likable",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Jo is warm",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Jo is approachable",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"I think Jo is funny",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Wells says things that make me laugh",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
  ],
};
var quiz5 = {
  quizn: 5,
  questions:[
    {
      q:"Gramps says funny things",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Jo is entertaining",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Q2.3",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Q2.4",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
    {
      q:"Q2.5",
      a:[
        "Disagree",
        "Somewhat Disagree",
        "Neutral",
        "Somewhat Agree",
        "Agree",
      ],
      response:-1,
      aclick:[], //IGNORE- WILL BE AUTOGENERATED
    }, 
  ],
};
var reset_quiz = function(quiz)
{
  for(var i = 0; i < quiz.questions.length; i++)
  {
    var q = quiz.questions[i];
    q.response = -1;
  }
}
var gen_callbacks = function(quiz)
{
  for(var i = 0; i < quiz.questions.length; i++)
  {
    var q = quiz.questions[i];
    for(var j = 0; j < q.a.length; j++)
      q.aclick[j] = (function(i, selection){
        return function() {
          if(quiz.questions[i].response == selection) {
            // if player re-clicks, deselect.
            quiz.questions[i].response = -1;
          }
          else {
            // else, select newly chosen item.
            quiz.questions[i].response = selection;
          }
        }
      })(i,j); //javascript is ridiculous
  }
}
var log_quiz = function(quiz)
{
  log_quiz_type_data = my_logger.get_quiz_type_data(quiz);
  log_quiz_subtype_data = my_logger.get_quiz_subtype_data();
  log_data = my_logger.get_log_data(LOG_TYPE_QUIZ,log_quiz_type_data,LOG_SUBTYPE_BASIC,log_quiz_subtype_data);
  my_logger.send_log(log_data);

}
gen_callbacks(quiz0);
gen_callbacks(quiz1);
gen_callbacks(quiz2);
gen_callbacks(quiz3);
gen_callbacks(quiz4);
gen_callbacks(quiz5);

var quiz = quiz0;
