var save_code = 0;
var save_table_code = 0;
var save_codes = [];
var save_table = [];

//must be in chronological order

save_codes.push("startgame");
save_table[save_codes[save_codes.length-1]] = {
  reqs:[[
  ]],
  code:"00000000000000000000000000000000000000000000000000000000000000000"
};

save_codes.push("notebook");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.closet.notebook",
],],
all:
[
"tunic.historicalsociety",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.doorblock",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
],
code:"050000000000000000000001048576812646400007670000000000000000000000000000000000000000000000000"
};

save_codes.push("wiscwonders");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.entry.groupconvo",
],],
all:
[
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.doorblock",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.boss",
"tunic.historicalsociety.entry.boss.talktogramps",
"tunic.historicalsociety.entry.wells",
"tunic.historicalsociety.entry.wells.talktogramps",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.block_tomap1",
"tunic.historicalsociety.entry.groupconvo",
],
code:"090000000000000000000003145728812646600007675423104000828000000000000000000000000000000000000"
};

save_codes.push("mysteryslip");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.collection.gramps.found",
],],
all:
[
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
],
code:"140000000000000000000000000608007372421938561051648000000000000000000012000000000000000000000"
};

save_codes.push("plaque");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.kohlcenter.halloffame.plaque.face.date",
],],
all:
[
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.doorblock",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.gramps.lost",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.boss",
"tunic.historicalsociety.entry.boss.talktogramps",
"tunic.historicalsociety.entry.wells",
"tunic.historicalsociety.entry.wells.talktogramps",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.block_tomap1",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.stacks",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
],
code:"140000000000000000000003145728812646641950715423867000828000000648126464000000800000000000000"
};

save_codes.push("notajersey");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.capitol.hall.chap1_finale_c",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.boss.talktogramps",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.doorblock",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.gramps.lost",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.boss",
"tunic.historicalsociety.entry.boss.talktogramps",
"tunic.historicalsociety.entry.wells",
"tunic.historicalsociety.entry.wells.talktogramps",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.block_tomap1",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.stacks",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
],
code:"000020830209715202785283145728812646641950715423867000828000000648126464000000800000000000000"
};

save_codes.push("trashed");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.closet_dirty",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
],
code:"060020822000000000000090000608020479621938881051648000000000000000001148000000000000000000000"
};

save_codes.push("archivist");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.frontdesk.archivist.have_glass",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist.need_glass_0",
"tunic.historicalsociety.frontdesk.archivist.need_glass_1",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
],
code:"100020822000000000000090000608361266821939125245952000927700000000001148000000000000000000000"
};

save_codes.push("expert");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist.need_glass_0",
"tunic.historicalsociety.frontdesk.archivist.need_glass_1",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
],
code:"130020822000000000000090000608361266821939125245952000927741919680001148000000000000000000000"
};

save_codes.push("logbook");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.drycleaner.frontdesk.logbook.page.bingo",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist.need_glass_0",
"tunic.historicalsociety.frontdesk.archivist.need_glass_1",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
],
code:"010020822000000001208090000608361266821939125245952000927741919680001148000000000000000000000"
};

save_codes.push("suffragist");
save_table[save_codes[save_codes.length-1]] = {
  reqs:[[
  "tunic.library.microfiche.reader.paper2.bingo",
  ]],
  all:
  [
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_plaquefirst_0",
"tunic.capitol.hall.boss.chap1_finale_plaquefirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
"tunic.library",
"tunic.library.frontdesk",
"tunic.library.frontdesk.worker",
"tunic.library.frontdesk.worker.hello",
"tunic.library.microfiche",
"tunic.library.microfiche.reader",
"tunic.library.microfiche.reader.paper0",
"tunic.library.microfiche.reader.paper0.prev",
"tunic.library.microfiche.reader.paper2",
"tunic.library.microfiche.reader.paper2.bingo",
],
  code:"13000290241492488373021206614702933590018463418963200965040001582",
};

save_codes.push("taxidermist");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.library.frontdesk.worker.wells",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist.need_glass_0",
"tunic.historicalsociety.frontdesk.archivist.need_glass_1",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
"tunic.library",
"tunic.library.frontdesk",
"tunic.library.frontdesk.worker",
"tunic.library.frontdesk.worker.hello",
"tunic.library.frontdesk.worker.wells",
"tunic.library.frontdesk.wellsbadge",
"tunic.library.frontdesk.wellsbadge.hub",
"tunic.library.microfiche",
"tunic.library.microfiche.reader",
"tunic.library.microfiche.reader.paper0",
"tunic.library.microfiche.reader.paper0.prev",
"tunic.library.microfiche.reader.paper2",
"tunic.library.microfiche.reader.paper2.bingo",
],
code:"150020822000000001208090000608361266821939125245952000927741919686593660001265700000000000000"
};

save_codes.push("stacks");
save_table[save_codes[save_codes.length-1]] = {
  reqs:[[
  "tunic.historicalsociety.stacks.journals.pic_2.bingo",
  ]],
  all:
  [
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_plaquefirst_0",
"tunic.capitol.hall.boss.chap1_finale_plaquefirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.newspaper",
"tunic.historicalsociety.frontdesk.archivist.recap",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
"tunic.library",
"tunic.library.frontdesk",
"tunic.library.frontdesk.worker",
"tunic.library.frontdesk.worker.hello",
"tunic.library.frontdesk.worker.wells",
"tunic.library.frontdesk.wellsbadge",
"tunic.library.frontdesk.wellsbadge.hub",
"tunic.library.microfiche",
"tunic.library.microfiche.reader",
"tunic.library.microfiche.reader.paper0",
"tunic.library.microfiche.reader.paper0.prev",
"tunic.library.microfiche.reader.paper2",
"tunic.library.microfiche.reader.paper2.bingo",
],
  code:"09000290241492488373021206614702933590019359418963219315120001582",
};

save_codes.push("photo");
save_table[save_codes[save_codes.length-1]] = {
  reqs:[[
  "tunic.historicalsociety.stacks.journals.pic_2.bingo"
  ]],
  all:
  [
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_plaquefirst_0",
"tunic.capitol.hall.boss.chap1_finale_plaquefirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.photo",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.newspaper",
"tunic.historicalsociety.frontdesk.archivist.recap",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.historicalsociety.stacks.journals",
"tunic.historicalsociety.stacks.journals.hub",
"tunic.historicalsociety.stacks.journals.hub.topics",
"tunic.historicalsociety.stacks.journals.pic_0",
"tunic.historicalsociety.stacks.journals.pic_0.next",
"tunic.historicalsociety.stacks.journals.pic_1",
"tunic.historicalsociety.stacks.journals.pic_1.next",
"tunic.historicalsociety.stacks.journals.pic_2",
"tunic.historicalsociety.stacks.journals.pic_2.bingo",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
"tunic.library",
"tunic.library.frontdesk",
"tunic.library.frontdesk.worker",
"tunic.library.frontdesk.worker.hello",
"tunic.library.frontdesk.worker.wells",
"tunic.library.frontdesk.wellsbadge",
"tunic.library.frontdesk.wellsbadge.hub",
"tunic.library.microfiche",
"tunic.library.microfiche.reader",
"tunic.library.microfiche.reader.paper0",
"tunic.library.microfiche.reader.paper0.prev",
"tunic.library.microfiche.reader.paper2",
"tunic.library.microfiche.reader.paper2.bingo",
],
  code:"09000290241492488373021206614702933598375199418963319315120001582",
};

save_codes.push("blowthisthingwideopen");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.stacks.journals.pic_2.bingo",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist.need_glass_0",
"tunic.historicalsociety.frontdesk.archivist.need_glass_1",
"tunic.historicalsociety.frontdesk.archivist.newspaper",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.historicalsociety.stacks.journals",
"tunic.historicalsociety.stacks.journals.hub",
"tunic.historicalsociety.stacks.journals.hub.topics",
"tunic.historicalsociety.stacks.journals.pic_0",
"tunic.historicalsociety.stacks.journals.pic_0.next",
"tunic.historicalsociety.stacks.journals.pic_1",
"tunic.historicalsociety.stacks.journals.pic_1.next",
"tunic.historicalsociety.stacks.journals.pic_2",
"tunic.historicalsociety.stacks.journals.pic_2.bingo",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
"tunic.library",
"tunic.library.frontdesk",
"tunic.library.frontdesk.worker",
"tunic.library.frontdesk.worker.hello",
"tunic.library.frontdesk.worker.wells",
"tunic.library.frontdesk.wellsbadge",
"tunic.library.frontdesk.wellsbadge.hub",
"tunic.library.microfiche",
"tunic.library.microfiche.reader",
"tunic.library.microfiche.reader.paper0",
"tunic.library.microfiche.reader.paper0.prev",
"tunic.library.microfiche.reader.paper2",
"tunic.library.microfiche.reader.paper2.bingo",
],
code:"000020822000000001208090000608361266821939125245952838156541919686593660001265700000000000000"
};

save_codes.push("mustfindteddy");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.basement.gramps.whatdo",
]],
all:
[
],
code:"0"
};

save_codes.push("scratches");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.basement.seescratches",
]],
all:
[
],
code:"0"
};

save_codes.push("hesalive");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.cage.teddy.trapped",
]],
all:
[
],
code:"0"
};

save_codes.push("theculprit");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.entry.directory.closeup.archivist",
]],
all:
[
],
code:"0"
};

save_codes.push("akey");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.frontdesk.key",
]],
all:
[
],
code:"0"
};

save_codes.push("rescued");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.cage.confrontation",
]],
all:
[
],
code:"0"
};

save_codes.push("backtowork");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.collection_flag.gramps.flag",
]],
all:
[
],
code:"0"
};

save_codes.push("sadanimals");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.wildlife.center.wells.nodeer",
]],
all:
[
],
code:"0"
};

save_codes.push("flaglady");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.flaghouse.entry.flag_girl.symbol",
]],
all:
[
],
code:"0"
};

save_codes.push("ecologists");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.library.microfiche.reader_flag.paper2.bingo",
]],
all:
[
],
code:"0"
};

save_codes.push("duedilligence");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.historicalsociety.frontdesk.archivist.confrontation",
]],
all:
[
],
code:"0"
};

save_codes.push("sunset");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.nelson.trail.hiker.question",
]],
all:
[
],
code:"0"
};

save_codes.push("exhibition");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.nelson.trail.hiker.question",
]],
all:
[
],
code:"0"
};

save_codes.push("ch3");
save_table[save_codes[save_codes.length-1]] = {
reqs:[[
"tunic.capitol.hall.chap2_finale_c",
],],
all:
[
"tunic.capitol",
"tunic.capitol.hall",
"tunic.capitol.hall.boss",
"tunic.capitol.hall.boss.chap1_finale_0",
"tunic.capitol.hall.boss.chap1_finale_1",
"tunic.capitol.hall.boss.chap1_finale_2",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_0",
"tunic.capitol.hall.boss.chap1_finale_slipfirst_1",
"tunic.capitol.hall.boss.chap2_finale_0",
"tunic.capitol.hall.boss.chap2_finale_1",
"tunic.capitol.hall.boss.chap2_finale_1_fail",
"tunic.capitol.hall.boss.chap2_finale_2",
"tunic.capitol.hall.boss.chap2_finale_3",
"tunic.capitol.hall.boss.chap2_finale_4",
"tunic.capitol.hall.boss.chap2_finale_5",
"tunic.capitol.hall.boss.chap2_finale_6",
"tunic.capitol.hall.boss.writeitup",
"tunic.capitol.hall.gramps.chap2_teddy_finale_0",
"tunic.capitol.hall.gramps.chap2_teddy_finale_1",
"tunic.capitol.hall.gramps.chap2_teddy_finale_2",
"tunic.capitol.hall.gramps.chap2_teddy_finale_3",
"tunic.capitol.hall.gramps.chap2_teddy_finale_4",
"tunic.capitol.hall.chap1_finale",
"tunic.capitol.hall.chap2_finale",
"tunic.capitol.hall.chap2_teddy_finale",
"tunic.capitol.hall.chap1_finale_c",
"tunic.capitol.hall.chap2_finale_c",
"tunic.drycleaner",
"tunic.drycleaner.frontdesk",
"tunic.drycleaner.frontdesk.worker",
"tunic.drycleaner.frontdesk.worker.done",
"tunic.drycleaner.frontdesk.worker.hub",
"tunic.drycleaner.frontdesk.worker.hub.toleo",
"tunic.drycleaner.frontdesk.worker.leo",
"tunic.drycleaner.frontdesk.logbook",
"tunic.drycleaner.frontdesk.logbook.page",
"tunic.drycleaner.frontdesk.logbook.page.bingo",
"tunic.historicalsociety",
"tunic.historicalsociety.basement",
"tunic.historicalsociety.basement.janitor",
"tunic.historicalsociety.closet",
"tunic.historicalsociety.closet.gramps",
"tunic.historicalsociety.closet.gramps.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0",
"tunic.historicalsociety.closet.teddy.intro_0_cs_0.next",
"tunic.historicalsociety.closet.teddy.intro_0_cs_5",
"tunic.historicalsociety.closet.notebook",
"tunic.historicalsociety.closet.notebook.hub",
"tunic.historicalsociety.closet.retirement_letter",
"tunic.historicalsociety.closet.retirement_letter.hub",
"tunic.historicalsociety.closet.intro",
"tunic.historicalsociety.closet_dirty",
"tunic.historicalsociety.closet_dirty.gramps",
"tunic.historicalsociety.closet_dirty.gramps.helpclean",
"tunic.historicalsociety.closet_dirty.gramps.news",
"tunic.historicalsociety.closet_dirty.trigger_coffee",
"tunic.historicalsociety.closet_dirty.trigger_scarf",
"tunic.historicalsociety.closet_dirty.what_happened",
"tunic.historicalsociety.collection",
"tunic.historicalsociety.collection.gramps",
"tunic.historicalsociety.collection.gramps.found",
"tunic.historicalsociety.collection.tunic",
"tunic.historicalsociety.collection.tunic.hub",
"tunic.historicalsociety.collection.tunic.hub.slip",
"tunic.historicalsociety.collection.tunic.slip",
"tunic.historicalsociety.collection.cs",
"tunic.historicalsociety.entry",
"tunic.historicalsociety.entry.report",
"tunic.historicalsociety.entry.report.closeup",
"tunic.historicalsociety.entry.groupconvo",
"tunic.historicalsociety.frontdesk",
"tunic.historicalsociety.frontdesk.archivist",
"tunic.historicalsociety.frontdesk.archivist.have_glass",
"tunic.historicalsociety.frontdesk.archivist.hello",
"tunic.historicalsociety.frontdesk.archivist.need_glass_0",
"tunic.historicalsociety.frontdesk.archivist.need_glass_1",
"tunic.historicalsociety.frontdesk.archivist.newspaper",
"tunic.historicalsociety.frontdesk.magnify",
"tunic.historicalsociety.stacks",
"tunic.historicalsociety.stacks.journals",
"tunic.historicalsociety.stacks.journals.hub",
"tunic.historicalsociety.stacks.journals.hub.topics",
"tunic.historicalsociety.stacks.journals.pic_0",
"tunic.historicalsociety.stacks.journals.pic_0.next",
"tunic.historicalsociety.stacks.journals.pic_1",
"tunic.historicalsociety.stacks.journals.pic_1.next",
"tunic.historicalsociety.stacks.journals.pic_2",
"tunic.historicalsociety.stacks.journals.pic_2.bingo",
"tunic.humanecology",
"tunic.humanecology.frontdesk",
"tunic.humanecology.frontdesk.worker",
"tunic.humanecology.frontdesk.worker.intro1",
"tunic.humanecology.frontdesk.worker.intro1.next1",
"tunic.humanecology.frontdesk.worker.intro2",
"tunic.humanecology.frontdesk.worker.intro2.next",
"tunic.humanecology.frontdesk.businesscards",
"tunic.humanecology.frontdesk.businesscards.card_0",
"tunic.humanecology.frontdesk.businesscards.card_0.next",
"tunic.humanecology.frontdesk.businesscards.card_1",
"tunic.humanecology.frontdesk.businesscards.card_1.next",
"tunic.humanecology.frontdesk.businesscards.card_bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.bingo",
"tunic.humanecology.frontdesk.businesscards.card_bingo.next",
"tunic.kohlcenter",
"tunic.kohlcenter.halloffame",
"tunic.kohlcenter.halloffame.plaque",
"tunic.kohlcenter.halloffame.plaque.face",
"tunic.kohlcenter.halloffame.plaque.face.date",
"tunic.kohlcenter.halloffame.togrampa",
"tunic.library",
"tunic.library.frontdesk",
"tunic.library.frontdesk.worker",
"tunic.library.frontdesk.worker.hello",
"tunic.library.frontdesk.worker.wells",
"tunic.library.frontdesk.wellsbadge",
"tunic.library.frontdesk.wellsbadge.hub",
"tunic.library.microfiche",
"tunic.library.microfiche.reader",
"tunic.library.microfiche.reader.paper0",
"tunic.library.microfiche.reader.paper0.prev",
"tunic.library.microfiche.reader.paper2",
"tunic.library.microfiche.reader.paper2.bingo",
],
code:"003068254034946101208310000608361266821939125245952838156541919686593660001265700000000000000"
};

var url_json = jsonFromURL();
var cookie;
if(url_json.save)
{
  save_code = url_json.save;
  setCookie("save", url_json.save, 100);
}
else save_code = getCookie("save");

var Game = function(init)
{
  var default_init =
  {
    width:640,
    height:320,
    container:"stage_container"
  }

  var self = this;
  doMapInitDefaults(init,init,default_init);

  var stage = new Stage({width:init.width,height:init.height,container:init.container});
  var scenes = [
    new NullScene(self, stage),
    new LoadingScene(self, stage),
    new MenuScene(self, stage),
    new GamePlayScene(self, stage),
  ];
  var cur_scene     =  0;
  var old_cur_scene = -1;

  self.resize = function(args)
  {
    document.getElementById(init.container).removeChild(stage.canv.canvas);
    if(args.stage) stage = args.stage;
    else stage = new Stage({width:args.width,height:args.height,container:init.container});
    for(var i = 0; i < scenes.length; i++)
      scenes[i].resize(stage);
  }

  var flip;
  var flop;
  self.begin = function()
  {
    self.nextScene();
    flip = Date.now();
    tick();
  };

  var tick = function()
  {
    requestAnimFrame(tick,stage.canv.canvas);
    scenes[cur_scene].tick();
    var slow = false;
    flop = Date.now();
    slow = flop-flip > 25;
    flip = flop;
    if(old_cur_scene == cur_scene && (DOUBLETIME || slow))
      scenes[cur_scene].tick();
    if(old_cur_scene == cur_scene) //still in same scene- draw
    {
      stage.clear();
      scenes[cur_scene].draw();
      stage.draw(); //blits from offscreen canvas to on screen one
    }
    old_cur_scene = cur_scene;
  };

  self.nextScene = function()
  {
    self.setScene(cur_scene+1);
  };

  self.setScene = function(i)
  {
    scenes[cur_scene].cleanup();
    cur_scene = i;
    scenes[cur_scene].ready();
  }
};

